// <auto-generated />
namespace CorreiaNetCRM.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Build000002 : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206250026417_Build.00.0002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVYy27bRhTdF+g/EFy1i2hsJy0Sg0qgyHZhJJID0862GJFX0qDzYDlDQfq2LvpJ/YXcEYdvPShHCNCdeOfOuY+5c3io//75N/iwFtxbQaqZkkP/cnDheyAjFTO5GPqZmb966394//NPwW0s1t7Xwu+19cOdUg/9pTHJNSE6WoKgeiBYlCqt5mYQKUForMjVxcU7cnlJACF8xPK84DGThgnYPuDjWMkIEpNRPlExcO3suBJuUb0pFaATGsHQH6s0BUanYMaPk0Hu73sjzijmEgKf+17y5vpZQ2hSJRdhQg2j/GmTAK7PKdfgMr9O3vRN/uLKJk+olMognJIvKt4vy8LCbrEBZmPT2hY39J91RlOm6k7o9gk2DQOavqQqgdRsHmHe3Hof+x5pbift/eXu7laby9C/l+b1le9NM87pjEPZMuxpaFQKf4CElBqIv1BjIMVZuI9hW0sneCvUVAkoouDZ4ID53h1bQ/wZ5MIsy0gTui4sV7/97nvPkuE84iaTZrAjs8NRP6sFkz8+bAhySc8aNn8+HHVk2EoVUT8qxYHKk1O/FZTxH576M0dCUKMItC4ruME5e2LiZKxt89FmYMHiU08Bfx4tZf9lGCuRZGhophiQ6rp3SQDZz1CGSC595DVrgrVpkUHuHoJpXl6kvwo+58BBwSY70ygDVjxLcqItCJnsYeRgQpMEu1hjaGfxQkfPr8LTyVHkGCTSOziyzLaMhK2nC2it2t7HcMdSbXBu6Izacx3Hout2tL1FoFaX20RcNb3YYH+7M9zxlhrspPh6E++wLoFsui0Rynz2vBzc3jCinKb7eX2seCbkkTfFIaycuOswuaU/giPhOoQz9cdwjFrHcKb+GI4f6xjO1B/D0WMdw5n6YzTJrnFAjZUTu1OjvE6bamtd1IC0BrA96qQz6y2d0b47h1in7VJGL9mnxTKBu/F9xGGLAnIX38PyVyy21z/caANiYB0G4d98zBnWWzlM"
                       + "qGRz0OZJ/QXI58hQb1vq8gXKj2gd8/+F/GO2F0eF3omKoq785Iqm0ZKmXfnwPcLubKgN3dYH9WRZNmPm+yTZubLapbhiPHBzNsVVZPqLoOtf945VJZkOxTxRQnWkQC8ldUhI5UyCLZrZbuVpRqn4sxJhL5RaXXILSP37OLgBzRYVhP1alhDZz9AKtPC5l3NVnA2WV8+ocGkd3QQMxWOno9SwOY0MLtuR2Erlr5Rn2/GbQXwvHzKDBzXSGsSMNz73AnI4/lZPNnMOHhL7pM9RAqbJ7OQ+yI8Z43GZ9133bu2DsAPjRhOzwk8FhFtsSqSpkj2BXPtuIAFp+fIJRMIRTD/IkK5gf27He9jsWHDD6CKlQjuMar/9u4bY/2vefwM18/1I4REAAA=="; }
        }
    }
}
