// <auto-generated />
namespace CorreiaNetCRM.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206232346038_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVX227bOBB9X6D/IOi9ZpJ2F91AbuE6ycLY2imipK8FLY1torxoScqwv60P/aT+wg6tu+SLkhoL7JtEDc8czuVw9PP7j+DDRnBvDdowJYf+5eDC90BGKmZyOfRTu3j9zv/w/tVvwW0sNt6Xwu6Ns8Od0gz9lbXJNSEmWoGgZiBYpJVRCzuIlCA0VuTq4uJPcnlJACF8xPK84CGVlgnYveDrWMkIEptSPlUxcJOv45dwh+rNqACT0AiG/lhpDYzOwI4fpoPM3vdGnFHkEgJf+F7y9vrJQGi1ksswoZZR/rhNAL8vKDeQM79O3vYlf3HlyBMqpbIIp+SLDu+Xx8KD3WIA7NbR2h1u6D+ZlGqm6kZo9jdsGwu49FmrBLTdPsCiuXUS+x5pbift/eXu7lbHZehPpH1z5XuzlHM651CGDGMaWqXhL5CgqYX4M7UWNNbCJIbdWTrOW65mSkDhBXODBeZ7d2wD8SeQS7sqPU3ppli5+v0P33uSDOsRN1mdwh5mx71+Uksm/3u3IcgVPavb7P2415Fla1V4/agUByqfTf2JY2uqUQTGlFg3mPFHJk4QCkhV1d1axya3lGH15H6wfd0SbGyr5jPzEGyzRrHLK/is1QdF0+ylUTqs5IRkelLoDjkgPMGUJgmmrCZE+YoX5ir0Ony+BogMg0RmjxSUbEtP2G50Ca2vTgBjuGPaWEwKnVOX0HEsumYnw1s4akW5rTdV0IsN7jnP4R4xHuxVsnoQ7/BcAkVjd0Qo+RzQwHxvGFFO9WH5GiueCnlCEI9hZfpUh8lW+iPkWlOHyJf6Y+TCUcfIl/pj5DJQx8iX+mM0VaAR3MaXLmJAWmluFxTpVFTr0mpX6LHebpuU3sseb/VykPdVn0mj1WiZie9hqNYsdk0Wbo0FMXAGg/AfPuYMz1sZTKlkCzD2UX0DvClRB961RpUXjBHEmJj/L2YJ5mJxcmp45vVUHyPkmupoRXX3Gv2VKeFs"
                       + "qI0hoA/qs+/4ObNnud9jzI099/3euad6XfPHbvmsAZHu3DHPaEZafK0mhBfOAV1NCEj9HyW4AcOWFYT7Y5EQuV+BCrSwmciFKmKOx6szKkxaKZmCpZgCOtKWLWhk8bNLz25o/EJ5iia3Yg7xRN6nNkntyBgQc94YuQNy3P9u2GlyDu4T92bOcQSkyVwV3cuPKeNxyfuuW5KHIFzB5EKBrHBoRrjltkSaKdkTKA/fDSQgncw8gkg4gpl7GdI1HOZ2OobNiAU3jC41FSbHqPa7X2bi/pnf/ws8FkK7ZQ8AAA=="; }
        }
    }
}
