// <auto-generated />
namespace CorreiaNetCRM.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Build000004 : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206250026417_Build.00.0004"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVY227bRhB9L9B/IPgere2kRWpQCRTZLoRGcmDaeS1W5EhadC/s7lKwvi0P/aT+QmfFJcWLLrQjBOibOJw5c9mZs0P9++2f6OOz4MEatGFKDsPLwUUYgExUyuRyGOZ28eZ9+PHDzz9Ft6l4Dr6Wem+dHlpKMwxX1mbXhJhkBYKagWCJVkYt7CBRgtBUkauLi9/I5SUBhAgRKwiih1xaJmD7gI9jJRPIbE75VKXAjZfjm3iLGsyoAJPRBIbhWGkNjM7Ajh+mg0I/DEacUYwlBr4Ig+zd9ZOB2Goll3FGLaP8cZMBvl9QbsBHfp296xv8xZULnlAplUU4JV+VfFilhYndYgHsxoW1TW4YPpmcaqbqSqj2B2waAhR90SoDbTcPsGiaTtIwIE1z0ravrLumLpZhOJH27VUYzHLO6ZxDVTKsaWyVht9BgqYW0i/UWtDYC5MUtrl0nLdczZSA0gueDTZYGNyxZ0g/g1zaVeVpSp9LydUvv4bBk2TYj2hkdQ57Ijvu9bNaMvnj3cYgV/Ssbovn415Hlq1V6fWTUhyofHHot4Iy/uMr9sSREdQoAWOqFG6w0R6ZOFGHiOyGqTtiyC2WMmxa7wdZw4ng2bZGrVCPwTZHA8llB18wzKCc1b1hVA53LEYKGivpjhzgu2hKswzLXeM/LwliT35v4pdTjygwSGL2MFAVbeUJp5wuofXW8W4Kd0wbi4dC59Qd6DgVXbWT5S0dtarcprld0UsD99uf4Z47YLCXQOtFvMO8BHLVNkWo4jlAvd42Tiin+jBrjhXPhTzBw8ewClqswxSS/gie4uoQXtQfw/NVHcOL+mN49qljeFF/DE8+dQwv6o/RZJLGATXedBEj0mqVdlOSTle27tt2lx/jh7ZK5b3iiRYfRH42+yxJrWEtVMIAS7VmqRvUeGMsiIFTGMR/8zFnmO9OYUolW4Cxj+ovwEseueR9a8t6xQZEjEn5/2INYq4WJxeeF15x"
                       + "9Q1IrqlOVlR3r9HvWXDOhtrYX/qgvng9mTP7favJ2XLdt3mkeOL23JtH5wbttYAc2z+KscZw5y7yIsxEiz93u8srN5Qu00Sk/tEW3YBhyx2E+4STkLhvox1oqTORC1XWHNOrR1SqtI5kCpbiEdCRtmxBE4uv3fFsV9GvlOfbXphDOpH3uc1yOzIGxJw3vkEictz/dg1rxhzdZ+7JnCMFDJO5LrqXn3LG0yruu25LHoJwDePpB6PCVRzhlpsKaaZkTyBfvhvIQDryegSRcQQz9zKmazgc2+kaNisW3TC61FQYj7Gzd/8hEPcnwof/AFbkQmp2EAAA"; }
        }
    }
}
