// <auto-generated />
namespace CorreiaNetCRM.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Build000001 : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206250026417_Build.00.0001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVY227bRhB9L9B/IPgere2kRWpQCRTZLoRGcmDaeS1W5EhadC/s7lKwvi0P/aT+QmfFJcWLLrQjBOibOJw9c2Z29uxQ/377J/r4LHiwBm2YksPwcnARBiATlTK5HIa5Xbx5H3788PNP0W0qnoOvpd9b54crpRmGK2uza0JMsgJBzUCwRCujFnaQKEFoqsjVxcVv5PKSAEKEiBUE0UMuLROwfcDHsZIJZDanfKpS4Mbb8U28RQ1mVIDJaALDcKy0BkZnYMcP00HhHwYjzihyiYEvwiB7d/1kILZayWWcUcsof9xkgO8XlBvwzK+zd33JX1w58oRKqSzCKfmq5MMqLUzsFgtgN47WNrlh+GRyqpmqO6HbH7BpGND0RasMtN08wKK5dJKGAWkuJ+311eruUsdlGE6kfXsVBrOcczrnUJUMaxpbpeF3kKCphfQLtRY09sIkhW0uneCtUDMloIyCe4MNFgZ37BnSzyCXdlVFmtLn0nL1y69h8CQZ9iMusjqHPcyOR/2slkz++LAxyBU9a9ji+XjUkWVrVUb9pBQHKl9M/VZQxn849SeOgqBGCRhTZXCDffbIxAmsiOzOUveEobRYyrBnfRwUDWeCZ9s6aYV7DLZ5MlBbdvCFwAzKo7qXRhVwJ2KkULFS7cgBuYumNMuw2jX585Yg9tr3Jn658ogCgyRmjwBVbKtIeMjpElpvneymcMe0sbgpdE7d/o9T0XU7Wd4yUKvKbZXbFb1c4H77PdxzBQz26me9iHeYl0Cp2qYIFZ8DyuvXxgnlVB8WzbHiuZAnZPgYVqGKdZjC0h/BK1wdwpv6Y3i5qmN4U38MLz51DG/qj+G1p47hTf0xmkrS2KDGmy5iRFqt0m5K0unK1nXb7vJj+tB2qaJXOtHSg8ifzT4zUuuwFi5hgKVas9Qd1HhjLIiBcxjEf/MxZ5jvzmFKJVuAsY/qL8A7HrXkfWvIesUARIxJ+f9iCmKuFifnnRde"
                       + "rPUBSK6pTlZUd2/R75lvzobaGF/6oL54Opkz+32TyblY7Rs8Utxwe+7Bo3OB9po/jo0fxalGunPHvKCZaPHnbnR55YDSFZqI1D/ZohswbLmDcB9wEhL3ZbQDLX0mcqHKmmN6dUalS2tLpmApbgEdacsWNLH42m3PdhD9Snm+bYU5pBN5n9sstyNjQMx54wskIsfjb6ewJufoPnNP5hwpIE3muuhefsoZTyved90+PwThGsarD7LCQRzhlpsKaaZkTyBfvhvIQDrtegSRcQQz9zKmazjM7XQNmxWLbhhdaiqMx9itd/8gEPcXwof/AAGnEFR0EAAA"; }
        }
    }
}
